services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      target: development
      args:
        - NODE_ENV=development
    container_name: whisper-wellness-frontend
    restart: unless-stopped
    ports:
      - "3001:3001"  # Vite dev server port
      - "9229:9229"  # For Node.js debug port
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules  # Keep node_modules in sync
    environment:
      - NODE_ENV=development
      - PORT=3001
      - HOST=0.0.0.0
      - VITE_API_URL=http://localhost:8002/api  # Point to FastAPI
    networks:
      - whisper-wellness-network
    depends_on:
      mongodb:
        condition: service_healthy
      whisper-wellness-qdrant:
        condition: service_started
    tty: true
    stdin_open: true

  mongodb:
    image: mongo:latest
    container_name: whisper-wellness-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ChangeMeToASecurePassword123!
      MONGO_INITDB_DATABASE: whisper_wellness
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - whisper-wellness-network

  whisper-wellness-qdrant:
    image: qdrant/qdrant:latest
    container_name: whisper-wellness-qdrant
    restart: unless-stopped
    ports:
      - "6335:6333"  # Changed from 6333 to 6335 to avoid conflict
      - "6336:6334"  # Changed from 6334 to 6336 to avoid conflict
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - whisper-wellness-network

  fastapi:
    build:
      context: ./apps/fastapi
      dockerfile: Dockerfile
      target: development
    container_name: whisper-wellness-fastapi
    restart: unless-stopped
    ports:
      - "8002:8002"  # FastAPI port
    volumes:
      - ./apps/fastapi:/app
      - /app/venv  # Keep Python virtual environment
      - ./mongo-cert.crt:/etc/ssl/certs/mongo-cert.crt:ro  # Mount MongoDB CA certificate
      - ./mongo.pem:/etc/ssl/certs/mongo.pem:ro  # Mount MongoDB client certificate
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONFAULTHANDLER=1
      - DEBUG=True
      - HOST=0.0.0.0
      - PORT=8002
      # Database connections (using non-SSL for development)
      - MONGODB_URI=mongodb://admin:ChangeMeToASecurePassword123!@mongodb:27017/whisper_wellness?authSource=admin
      - MONGODB_DB=whisper_wellness
      - QDRANT_URL=http://whisper-wellness-qdrant:6333
      - QDRANT_COLLECTION=whisper_wellness
      # Security
      - SECRET_KEY=your-secret-key-here
      - ACCESS_TOKEN_EXPIRE_MINUTES=11520
    depends_on:
      mongodb:
        condition: service_healthy
      whisper-wellness-qdrant:
        condition: service_started
    networks:
      - whisper-wellness-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  whisper-wellness-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  qdrant_data:
    name: whisper-wellness-qdrant-data
  mongodb_data:
    name: whisper-wellness-mongodb-data
  mongodb_config:
    name: whisper-wellness-mongodb-config
